/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ygy_myjnitest_JNI */

#ifndef _Included_com_ygy_myjnitest_JNI
#define _Included_com_ygy_myjnitest_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ygy_myjnitest_JNI
 * Method:    Hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ygy_myjnitest_JNI_Hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
